# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
  packages: write   # <-- needed to push to GHCR

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set image tag (v1, v2, v3...)
        id: vars
        run: echo "TAG=v${GITHUB_RUN_NUMBER}" >> $GITHUB_OUTPUT
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}
      #- run: docker build . -t ghcr.io/tarunp2912/bus-app:${{ steps.vars.outputs.TAG }}
      #- run: docker push ghcr.io/tarunp2912/bus-app:${{ steps.vars.outputs.TAG }}
      # - name: Build & Push (second method to push)
      #   run: |
      #     IMAGE=ghcr.io/${{ github.repository_owner }}/bus-app
      #     docker build . -t $IMAGE:${{ steps.vars.outputs.TAG }}
      #     docker push $IMAGE:${{ steps.vars.outputs.TAG }}

      
      # Only Build The Image
      # - name: Build Docker image
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: .
      #     push: false   # Only build, don't push yet
      #     tags: | 
      #       ghcr.io/${{ github.repository }}/bus-app:latest
      #       ghcr.io/${{ github.repository }}/bus-app:${{ steps.vars.outputs.TAG }}
            
      # Build and Push In One Step
      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true  # Push the image
          tags: |
            ghcr.io/${{ github.repository }}/testing:latest
            ghcr.io/${{ github.repository }}/testing:${{ steps.vars.outputs.TAG }}
